# syntax=docker.io/docker/dockerfile:1

FROM node:24-alpine AS base

# builder
FROM base AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_URL
ARG ADMIN_USER_PASSWORD
ARG BT_USER_PASSWORD
ARG SESSION_SECRET
ARG DATABASE_URL

ENV NEXT_PUBLIC_URL
ENV ADMIN_USER_PASSWORD
ENV BT_USER_PASSWORD
ENV SESSION_SECRET
ENV DATABASE_URL

ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci

COPY . .

RUN npx prisma migrate deploy
RUN npx prisma generate
RUN npx ts-node --transpile-only ./scripts/basetime-org-setup.ts
RUN npx ts-node --transpile-only ./scripts/admin-user-setup.ts
RUN npm run build

# runner
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --chown=nextjs:nodejs prisma ./prisma/

USER nextjs

EXPOSE 3000